### ISSUE TITLE
vs连接调试，显示无法握手

### ISSUE THREAD

**Issue by edimax82** [wilinz/AutoX#1]
1. Autox.js 版本：634
2. Autox.js 下载渠道：https://github.com/wilinz/AutoX/devtest
3. Android 版本：Android 8
4. Android 机型：小米6
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：1.4.1
7. 问题描述：vs连接调试，显示握手失败
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by edimax82** [comment]
kotlin build.gradle 版本

**Comment by wilinz** [comment]
更新VSCODE Autox.js 扩展

**Comment by edimax82** [comment]
需要安装哪个版本的 VSCODE Autox.js 扩展
